# Generated by Django 4.2.4 on 2023-09-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_app', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
